version: '3'

services:
  mysql:
    container_name: sample-mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "sample"
      MYSQL_ROOT_PASSWORD: "docker"
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mysql-network
volumes:
  mysql-volume: null
networks:
  mysql-network:
    driver: bridge
